### ISSUE TITLE
Errors on production

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#180]
```
TypeError: Cannot read property 'endsWith' of undefined
  at /app/lib/periodicChecks.js:157:31
  at Array.some (<anonymous>)
  at /app/lib/periodicChecks.js:156:51
  at Array.filter (<anonymous>)
  at Object.ensureAllIssuesHaveProjects (/app/lib/periodicChecks.js:155:47)
  at async Promise.all (index 1)
  at async runChecks (/app/index.js:129:13)
  at async /app/index.js:181:7
```

```
 09:53:42.384Z ERROR event: Cannot read property 'split' of undefined (id=6374b3f0-4ce0-11eb-92bf-82d148a0655f)
Jan 02 01:53:42   TypeError: Cannot read property 'split' of undefined
Jan 02 01:53:42       at getNewItemsFromFileByRegex (/app/lib/utils.js:79:35)
Jan 02 01:53:42       at getNewJobsFromFile (/app/lib/checkPullRequestJob.js:46:10)
Jan 02 01:53:42       at addsNewJob (/app/lib/checkPullRequestJob.js:53:19)
Jan 02 01:53:42       at /app/lib/checkPullRequestJob.js:189:45
Jan 02 01:53:42       at Array.filter (<anonymous>)
Jan 02 01:53:42       at Object.checkForNewJob (/app/lib/checkPullRequestJob.js:188:38)
Jan 02 01:53:42       at async runChecks (/app/index.js:91:13)
Jan 02 01:53:42       at async /app/index.js:233:7
Jan 02 01:53:42   --
Jan 02 01:53:42   event: {
Jan 02 01:53:42     "event": "pull_request.synchronize",
Jan 02 01:53:42     "id": "6374b3f0-4ce0-11eb-92bf-82d148a0655f",
Jan 02 01:53:42     "installation": 213174,
Jan 02 01:53:42     "repository": "oppia/oppia"
Jan 02 01:53:42   }
```

**Comment by vojtechjelinek** [comment]
@jameesjohn Only one error from this issue is fixed, so reopening this

**Comment by jameesjohn** [comment]
Right
